name: Build and Test

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm install
      - run: npm run compile --if-present
      - run: npm run lint
      - run: xvfb-run -a npm run test
      - name: Install vsce
        run: npm install -g vsce

      - name: Package extension (.vsix)
        run: |
          # Ensure compiled files exist
          npm run compile --if-present
          # Create a versioned vsix in the workspace
          vsce package -o extension.vsix || echo 'vsce package failed'

      - name: Upload VSIX artifact
        uses: actions/upload-artifact@v4
        with:
          name: extension-vsix
          path: extension.vsix
